import type { CalendarEvent } from './types'

export const MOCK_EVENTS: CalendarEvent[] = [
  {
    id: '1',
    title: 'Reels: Workspace',
    platform: 'instagram',
    date: '2025-04-02',
    time: '09:00',
    description: 'Showcasing the new Infinity Creators setup with the obsidian theme inspiration.',
    tags: ['creative', 'workspace'],
    status: 'published',
    reachEstimate: '8.2K',
    engagementRate: '4.8%',
  },
  {
    id: '2',
    title: 'X: Growth Thread',
    platform: 'x',
    date: '2025-04-05',
    time: '14:30',
    description: 'Thread about creator economy growth strategies for Q2.',
    tags: ['growth', 'strategy'],
    status: 'published',
  },
  {
    id: '3',
    title: 'Threads: Community',
    platform: 'threads',
    date: '2025-04-09',
    time: '10:00',
    description: 'Community engagement post about design tools.',
    status: 'published',
  },
  {
    id: '4',
    title: 'IG: Design Tips',
    platform: 'instagram',
    date: '2025-04-11',
    time: '09:00',
    description: 'Carousel with 5 design tips for content creators.',
    tags: ['design', 'tips'],
    status: 'published',
  },
  {
    id: '5',
    title: 'X: Update Thread',
    platform: 'x',
    date: '2025-04-11',
    time: '15:00',
    description: 'Product update thread showcasing new features.',
    status: 'published',
  },
  {
    id: '6',
    title: 'Aesthetic Desk Tour',
    platform: 'instagram',
    date: '2025-04-18',
    time: '09:00',
    description: 'Showcasing the new Infinity Creators setup with the obsidian theme inspiration.',
    tags: ['creative', 'workspace'],
    status: 'scheduled',
    reachEstimate: '12.4K',
    engagementRate: '5.2%',
  },
  {
    id: '7',
    title: '"How to build an Atelier UI..."',
    platform: 'x',
    date: '2025-04-18',
    time: '14:30',
    description: '"Today we dive into the Kinetic Atelier design system and why we skip the 1px borders..."',
    status: 'scheduled',
  },
  {
    id: '8',
    title: 'LinkedIn: Case Study',
    platform: 'linkedin',
    date: '2025-04-22',
    time: '08:00',
    description: 'Case study on how AI-powered content creation increased engagement by 300%.',
    tags: ['case-study', 'AI'],
    status: 'draft',
  },
  {
    id: '9',
    title: 'TH: Quick Tip',
    platform: 'threads',
    date: '2025-04-25',
    time: '12:00',
    description: 'Quick tip on using Voice DNA for better content.',
    status: 'draft',
  },
]
